### ISSUE TITLE
Hey Joe!

### ISSUE THREAD

**Issue by pdbartsch** [oeon/oeon.github.io#2]
I enjoyed the sneak preview of your holiday letter and happy to hear you had what sounds like a very good year.  Not sure about this commenting platform though :)
I hope you and Paula are able to enjoy some time off for the holidays and here's to a great 2019!

**Comment by oeon** [comment]
LOL! Right on @pdbartsch - good to hear from you. I'm glad you enjoyed the post. It was indeed a good year, but not perfect, since we didn't catch a beer together. Let's change that next year ;) Cheers to you and yours this holiday season and let's hope for the best in 2019.
